<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Rankfoundry\eBaySDK\Shopping\Services;

class ShoppingService extends \Rankfoundry\eBaySDK\Shopping\Services\ShoppingBaseService
{
    const API_VERSION = '1027';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\FindProductsRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\FindProductsResponseType
     */
    public function findProducts(\Rankfoundry\eBaySDK\Shopping\Types\FindProductsRequestType $request)
    {
        return $this->findProductsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\FindProductsRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProductsAsync(\Rankfoundry\eBaySDK\Shopping\Types\FindProductsRequestType $request)
    {
        return $this->callOperationAsync(
            'FindProducts',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\FindProductsResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GetCategoryInfoResponseType
     */
    public function getCategoryInfo(\Rankfoundry\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request)
    {
        return $this->getCategoryInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCategoryInfoAsync(\Rankfoundry\eBaySDK\Shopping\Types\GetCategoryInfoRequestType $request)
    {
        return $this->callOperationAsync(
            'GetCategoryInfo',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GetCategoryInfoResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetItemStatusRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GetItemStatusResponseType
     */
    public function getItemStatus(\Rankfoundry\eBaySDK\Shopping\Types\GetItemStatusRequestType $request)
    {
        return $this->getItemStatusAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetItemStatusRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getItemStatusAsync(\Rankfoundry\eBaySDK\Shopping\Types\GetItemStatusRequestType $request)
    {
        return $this->callOperationAsync(
            'GetItemStatus',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GetItemStatusResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GetMultipleItemsResponseType
     */
    public function getMultipleItems(\Rankfoundry\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request)
    {
        return $this->getMultipleItemsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMultipleItemsAsync(\Rankfoundry\eBaySDK\Shopping\Types\GetMultipleItemsRequestType $request)
    {
        return $this->callOperationAsync(
            'GetMultipleItems',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GetMultipleItemsResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GetShippingCostsResponseType
     */
    public function getShippingCosts(\Rankfoundry\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request)
    {
        return $this->getShippingCostsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShippingCostsAsync(\Rankfoundry\eBaySDK\Shopping\Types\GetShippingCostsRequestType $request)
    {
        return $this->callOperationAsync(
            'GetShippingCosts',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GetShippingCostsResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetSingleItemRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GetSingleItemResponseType
     */
    public function getSingleItem(\Rankfoundry\eBaySDK\Shopping\Types\GetSingleItemRequestType $request)
    {
        return $this->getSingleItemAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetSingleItemRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSingleItemAsync(\Rankfoundry\eBaySDK\Shopping\Types\GetSingleItemRequestType $request)
    {
        return $this->callOperationAsync(
            'GetSingleItem',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GetSingleItemResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetUserProfileRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GetUserProfileResponseType
     */
    public function getUserProfile(\Rankfoundry\eBaySDK\Shopping\Types\GetUserProfileRequestType $request)
    {
        return $this->getUserProfileAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GetUserProfileRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserProfileAsync(\Rankfoundry\eBaySDK\Shopping\Types\GetUserProfileRequestType $request)
    {
        return $this->callOperationAsync(
            'GetUserProfile',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GetUserProfileResponseType'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request
     * @return \Rankfoundry\eBaySDK\Shopping\Types\GeteBayTimeResponseType
     */
    public function geteBayTime(\Rankfoundry\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request)
    {
        return $this->geteBayTimeAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function geteBayTimeAsync(\Rankfoundry\eBaySDK\Shopping\Types\GeteBayTimeRequestType $request)
    {
        return $this->callOperationAsync(
            'GeteBayTime',
            $request,
            '\Rankfoundry\eBaySDK\Shopping\Types\GeteBayTimeResponseType'
        );
    }
}
