<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Rankfoundry\eBaySDK\ReturnManagement\Services;

class ReturnManagementService extends \Rankfoundry\eBaySDK\ReturnManagement\Services\ReturnManagementBaseService
{
    const API_VERSION = '1.1.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetVersionRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\GetVersionResponse
     */
    public function getVersion(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\GetVersionResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetUserReturnsRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\GetUserReturnsResponse
     */
    public function getUserReturns(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetUserReturnsRequest $request)
    {
        return $this->getUserReturnsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetUserReturnsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserReturnsAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetUserReturnsRequest $request)
    {
        return $this->callOperationAsync(
            'getUserReturns',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\GetUserReturnsResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnDetailRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnDetailResponse
     */
    public function getReturnDetail(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnDetailRequest $request)
    {
        return $this->getReturnDetailAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnDetailRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnDetailAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnDetailRequest $request)
    {
        return $this->callOperationAsync(
            'getReturnDetail',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnDetailResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetActivityOptionsRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\GetActivityOptionsResponse
     */
    public function getActivityOptions(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->getActivityOptionsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetActivityOptionsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getActivityOptionsAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->callOperationAsync(
            'getActivityOptions',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\GetActivityOptionsResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\IssueRefundRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\IssueRefundResponse
     */
    public function issueRefund(\Rankfoundry\eBaySDK\ReturnManagement\Types\IssueRefundRequest $request)
    {
        return $this->issueRefundAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\IssueRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issueRefundAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\IssueRefundRequest $request)
    {
        return $this->callOperationAsync(
            'issueRefund',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\IssueRefundResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideSellerInfoRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideSellerInfoResponse
     */
    public function provideSellerInfo(\Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideSellerInfoRequest $request)
    {
        return $this->provideSellerInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideSellerInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideSellerInfoAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideSellerInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideSellerInfo',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideSellerInfoResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnMetadataRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnMetadataResponse
     */
    public function getReturnMetadata(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnMetadataRequest $request)
    {
        return $this->getReturnMetadataAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnMetadataRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getReturnMetadataAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnMetadataRequest $request)
    {
        return $this->callOperationAsync(
            'getReturnMetadata',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\GetReturnMetadataResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideTrackingInfoRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideTrackingInfoResponse
     */
    public function provideTrackingInfo(\Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->provideTrackingInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideTrackingInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideTrackingInfoAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideTrackingInfo',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\ProvideTrackingInfoResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\SetItemAsReceivedRequest $request
     * @return \Rankfoundry\eBaySDK\ReturnManagement\Types\SetItemAsReceivedResponse
     */
    public function setItemAsReceived(\Rankfoundry\eBaySDK\ReturnManagement\Types\SetItemAsReceivedRequest $request)
    {
        return $this->setItemAsReceivedAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ReturnManagement\Types\SetItemAsReceivedRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setItemAsReceivedAsync(\Rankfoundry\eBaySDK\ReturnManagement\Types\SetItemAsReceivedRequest $request)
    {
        return $this->callOperationAsync(
            'setItemAsReceived',
            $request,
            '\Rankfoundry\eBaySDK\ReturnManagement\Types\SetItemAsReceivedResponse'
        );
    }
}
