<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Rankfoundry\eBaySDK\ProductMetadata\Services;

class ProductMetadataService extends \Rankfoundry\eBaySDK\ProductMetadata\Services\ProductMetadataBaseService
{
    const API_VERSION = '1.3.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchNamesResponse
     */
    public function getProductSearchNames(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request)
    {
        return $this->getProductSearchNamesAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchNamesAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchNamesRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchNames',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchNamesResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesResponse
     */
    public function getCompatibilitySearchNames(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request)
    {
        return $this->getCompatibilitySearchNamesAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchNamesAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchNames',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchNamesResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse
     */
    public function getProductSearchValues(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request)
    {
        return $this->getProductSearchValuesAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchValuesAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchValues',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse
     */
    public function getProductSearchValuesBulk(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request)
    {
        return $this->getProductSearchValuesBulkAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchValuesBulkAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchValuesBulk',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesResponse
     */
    public function getCompatibilitySearchValues(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request)
    {
        return $this->getCompatibilitySearchValuesAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchValuesAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchValues',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkResponse
     */
    public function getCompatibilitySearchValuesBulk(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request)
    {
        return $this->getCompatibilitySearchValuesBulkAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchValuesBulkAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchValuesBulk',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchValuesBulkResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionResponse
     */
    public function getProductSearchDataVersion(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request)
    {
        return $this->getProductSearchDataVersionAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSearchDataVersionAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSearchDataVersion',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetProductSearchDataVersionResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionResponse
     */
    public function getCompatibilitySearchDataVersion(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request)
    {
        return $this->getCompatibilitySearchDataVersionAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompatibilitySearchDataVersionAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getCompatibilitySearchDataVersion',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\GetCompatibilitySearchDataVersionResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request
     * @return \Rankfoundry\eBaySDK\ProductMetadata\Types\ProductMetadataBulkResponse
     */
    public function getProductMetadataBulk(\Rankfoundry\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request)
    {
        return $this->getProductMetadataBulkAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductMetadataBulkAsync(\Rankfoundry\eBaySDK\ProductMetadata\Types\ProductMetadataBulkRequest $request)
    {
        return $this->callOperationAsync(
            'getProductMetadataBulk',
            $request,
            '\Rankfoundry\eBaySDK\ProductMetadata\Types\ProductMetadataBulkResponse'
        );
    }
}
