<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace Rankfoundry\eBaySDK\ResolutionCaseManagement\Services;

class ResolutionCaseManagementService extends \Rankfoundry\eBaySDK\ResolutionCaseManagement\Services\ResolutionCaseManagementBaseService
{
    const API_VERSION = '1.3.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetVersionResponse
     */
    public function getVersion(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetVersionResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesResponse
     */
    public function getUserCases(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request)
    {
        return $this->getUserCasesAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserCasesAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesRequest $request)
    {
        return $this->callOperationAsync(
            'getUserCases',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetUserCasesResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailResponse
     */
    public function getEBPCaseDetail(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request)
    {
        return $this->getEBPCaseDetailAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEBPCaseDetailAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailRequest $request)
    {
        return $this->callOperationAsync(
            'getEBPCaseDetail',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsResponse
     */
    public function getActivityOptions(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->getActivityOptionsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getActivityOptionsAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsRequest $request)
    {
        return $this->callOperationAsync(
            'getActivityOptions',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\GetActivityOptionsResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundResponse
     */
    public function issueFullRefund(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request)
    {
        return $this->issueFullRefundAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issueFullRefundAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundRequest $request)
    {
        return $this->callOperationAsync(
            'issueFullRefund',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssueFullRefundResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoResponse
     */
    public function provideTrackingInfo(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->provideTrackingInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideTrackingInfoAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideTrackingInfo',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideTrackingInfoResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionResponse
     */
    public function offerOtherSolution(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request)
    {
        return $this->offerOtherSolutionAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function offerOtherSolutionAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionRequest $request)
    {
        return $this->callOperationAsync(
            'offerOtherSolution',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferOtherSolutionResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportResponse
     */
    public function escalateToCustomerSupport(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request)
    {
        return $this->escalateToCustomerSupportAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function escalateToCustomerSupportAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportRequest $request)
    {
        return $this->callOperationAsync(
            'escalateToCustomerSupport',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\EscalateToCustomerSupportResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportResponse
     */
    public function appealToCustomerSupport(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request)
    {
        return $this->appealToCustomerSupportAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function appealToCustomerSupportAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportRequest $request)
    {
        return $this->callOperationAsync(
            'appealToCustomerSupport',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\AppealToCustomerSupportResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundResponse
     */
    public function offerPartialRefund(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request)
    {
        return $this->offerPartialRefundAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function offerPartialRefundAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundRequest $request)
    {
        return $this->callOperationAsync(
            'offerPartialRefund',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferPartialRefundResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundResponse
     */
    public function issuePartialRefund(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request)
    {
        return $this->issuePartialRefundAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function issuePartialRefundAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundRequest $request)
    {
        return $this->callOperationAsync(
            'issuePartialRefund',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\IssuePartialRefundResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoResponse
     */
    public function provideShippingInfo(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request)
    {
        return $this->provideShippingInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideShippingInfoAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideShippingInfo',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideShippingInfoResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoResponse
     */
    public function provideReturnInfo(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request)
    {
        return $this->provideReturnInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideReturnInfoAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideReturnInfo',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideReturnInfoResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoResponse
     */
    public function provideRefundInfo(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request)
    {
        return $this->provideRefundInfoAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function provideRefundInfoAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoRequest $request)
    {
        return $this->callOperationAsync(
            'provideRefundInfo',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\ProvideRefundInfoResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsResponse
     */
    public function uploadDocuments(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request)
    {
        return $this->uploadDocumentsAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadDocumentsAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsRequest $request)
    {
        return $this->callOperationAsync(
            'uploadDocuments',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\UploadDocumentsResponse'
        );
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request
     * @return \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnResponse
     */
    public function offerRefundUponReturn(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request)
    {
        return $this->offerRefundUponReturnAsync($request)->wait();
    }

    /**
     * @param \Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function offerRefundUponReturnAsync(\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnRequest $request)
    {
        return $this->callOperationAsync(
            'offerRefundUponReturn',
            $request,
            '\Rankfoundry\eBaySDK\ResolutionCaseManagement\Types\OfferRefundUponReturnResponse'
        );
    }
}
